import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import PropertyPreview from './components/PropertyPreview';

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={
          <div className="container" style={{textAlign: 'center', marginTop: '20vh'}}>
            <h1 className="animate-fade-in">Property CRM WhatsApp Bot</h1>
            <p className="animate-fade-in delay-1" style={{marginTop: '1rem', fontSize: '1.2rem'}}>
              Welcome! To view a property, you need a valid preview link generated by the WhatsApp Bot. 
            </p>
            <p className="animate-fade-in delay-2" style={{marginTop: '1rem'}}>
              Send <strong>!addproperty</strong> to your WhatsApp bot to generate a link!
            </p>
          </div>
        } />
        <Route path="/preview/:id" element={<PropertyPreview />} />
        <Route path="*" element={<div className="container" style={{textAlign: 'center', marginTop: '20vh'}}><h2>404 - Not Found</h2></div>} />
      </Routes>
    </Router>
  );
}

export default App;
